### ISSUE TITLE
Linking to fortran

### ISSUE THREAD

**Issue by jeroen** [r-hub/homebrew-cran#2]
Packages that link to gfortran get a linking error. The problem is that `R CMD config FLIBS` hardcodes the runtime libs to be in `/usr/local/gfortran`. However with homebrew, gfortran is included with the `gcc` package and the libs are in `/usr/local/opt/gcc/lib/gcc/7`.

One workaround is to symlink the dir but this also has dynlibs, plus it requires sudo:

```sh
sudo ln -sf /usr/local/opt/gcc/lib/gcc/7 /usr/local/gfortran
```

Other workaround is to link fortran static libs to global dir:
```sh
ln -sf /usr/local/opt/gcc/lib/gcc/7/libgfortran.a /usr/local/lib/
ln -sf /usr/local/opt/gcc/lib/gcc/7/libquadmath.a /usr/local/lib/
```

**Comment by gaborcsardi** [comment]
We can install gfortran, from the CRAN download.

**Comment by jeroen** [comment]
Indeed, using the same `gfortran` as CRAN uses is the only reliable way. Updated the readme.
